name: busca_error
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8
  http: ^1.1.0 # Agrega esta línea
  archive: ^3.4.9  # 
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


  

flutter:
  uses-material-design: true

  assets:
  
    - assets/backgrounds/
    - assets/avatar/
    - assets/icons/ 

 
